version: "3.8"

networks:
  dev_network:

services:

  relay-app:
    container_name: relay-app
    environment:
      DATABASE_URL: jdbc:postgresql://relay-db:5432/nostr
    depends_on:
      - relay-db
    restart: unless-stopped
    build: .
    ports:
      - "6724:6724"
    networks:
      - dev_network

  relay-db:
    container_name: relay-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rushmi0
      POSTGRES_PASSWORD: sql@min
      POSTGRES_DB: nostr
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "5432:5432"


  relay-cache:
    container_name: relay-cache
    image: redis:7.0-alpine
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "6379:6379"
