version: "3.8"

networks:
  dev_network:
    driver: bridge

services:

  relay-db:
    container_name: relay-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rushmi0
      POSTGRES_PASSWORD: sql@min
      POSTGRES_DB: nostr
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "5432:5432"

  relay-app-native:
    container_name: fenrir-s-native
    build:
      context: .
      dockerfile: Dockerfile.native
    depends_on:
      - relay-db
    ports:
      - "6724:6724"
    networks:
      - dev_network

  relay-app-jvm:
    container_name: fenrir-s-jvm
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.jvm
    depends_on:
      - relay-db
    ports:
      - "6724:6724"
    networks:
      - dev_network

#  cloudflared-tunnel:
#    container_name: cloudflared-tunnel
#    image: cloudflare/cloudflared:latest
#    restart: unless-stopped
#    command: tunnel --no-autoupdate run --token

