version: "3.8"

networks:
  dev_network:

services:

  relay-app:
    container_name: relay-app
    image: amazoncorretto:21.0.3
    depends_on:
      - relay-db
    #restart: unless-stopped
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: >
      /bin/bash -c "./gradlew assemble && java -cp build/libs/*:build/docker/optimized/layers/app/* org.fenrirs.ApplicationKt"
    ports:
      - "6724:6724"
    networks:
      - dev_network

  relay-db:
    container_name: relay-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rushmi0
      POSTGRES_PASSWORD: sql@min
      POSTGRES_DB: nostr
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "5432:5432"

  relay-cache:
    container_name: relay-cache
    image: redis:7.0-alpine
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "6379:6379"
