micronaut.application.name = 'fenrir-s'

[micronaut.server]
cors.enabled = true
cors.localhost-pass-through = true
maxRequestSize = "1MB"
host = "localhost"
port = 6724

[micronaut.executors.scheduled]
type = "scheduled"
virtual = true
parallelism = 64
core-pool-size = 32


#################################################################################

[nostr.relay.info]
name = "rushmi0"
description = "นึกแล้ว มึงต้องอ่าน"
npub = 'npub1ujevvncwfe22hv6d2cjv6pqwqhkvwlcvge7vgm3vcn2max9tu03sgze8ry'
contact = "Lorem@bitkuy.com"

#################################################################################

[nostr.relay.policy.follows]
pass = true

[nostr.relay.policy.proof-of-work]
enabled = true
difficulty-minimum = 32

[nostr.relay.profile.backup]
enabled = true
sync = [
    "wss://relay-jp.nostr.wirednet.jp",
    "wss://r.kojira.io",
    "wss://relay.notoshi.win",
    "wss://relay.siamstr.com",
    "wss://relay.damus.io",
    "wss://relay.nostr.band",
    "wss://nostr-01.yakihonne.com"
]


#################################################################################

[jooq.datasources.default]
sql-dialect = "postgres"

[datasources.default]
#jdbc-url = "jdbc:postgresql://localhost:5432/nostr"
jdbc-url = "jdbc:postgresql://relay-db:5432/nostr"
driver-class-name = "org.postgresql.Driver"
username = "rushmi0"
password = "sql@min"
db-type = "postgres"
## Hikari Connection Pooling ##
minimum-idle = 5
maximum-pool-size = 10
idle-timeout = 60000
transaction-isolation = "TRANSACTION_REPEATABLE_READ"
keepalive-time = 60000
max-lifetime = 2000000
leak-detection-threshold = 30000
validation-timeout = 3000

[redis]
uri = "redis://localhost:6379"
timeout = "45m"
io-thread-pool-size = 5
computation-thread-pool-size = 4

[micronaut.router.static-resources.default]
mapping = "/**"
paths = ["classpath:public/"]
